### ISSUE TITLE
Compile error in `mix ecto.create Repo`

### ISSUE THREAD

**Issue by zw963** [jw2013/elixir-china#62]
```sh
== Compilation error on file lib/phoenix/socket.ex ==
** (ArgumentError) Access is not a protocol, cannot derive Access for Phoenix.Socket
    (elixir) lib/protocol.ex:76: Protocol.assert_protocol!/2
    (elixir) lib/protocol.ex:591: Protocol.derive/5
    (stdlib) lists.erl:1336: :lists.foreach/2
    (elixir) lib/protocol.ex:579: Protocol.__derive__/3
    lib/phoenix/socket.ex:24: (module)

could not compile dependency :phoenix, "mix compile" failed. You can recompile this dependency with "mix deps.compile phoenix", update it with "mix deps.update phoenix" or clean it with "mix deps.clean phoenix"
```

Elixir version 1.1.1

erlang version:  Erlang/OTP 17 [erts-6.3] [source] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false]

**Comment by zw963** [comment]
install newest erlang:

```sh
Erlang/OTP 18 [erts-7.1] [source] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false]
```
still exist this problem.

**Comment by zw963** [comment]
这么久没人问，晕哦，难道因为我的英文太烂吗？

**Comment by zw963** [comment]
Elixir version switch to 1.0.3, worked. 

Thanks.
