### ISSUE TITLE
setup error ?

### ISSUE THREAD

**Issue by mydearxym** [jw2013/elixir-china#72]
love your work!

i follow the install steps cause errors : 

```bash
➜ elixir-china git:(master) mix ecto.migrate Repo

19:37:09.757 [error] GenServer #PID<0.192.0> terminating
** (stop) %Postgrex.Error{message: "tcp connect: connection refused - :econnrefused", postgres: nil}
Last message: nil
State: [password: :REDACTED, timeout: 5000, otp_app: :elixir_china, repo: ElixirChina.Repo, adapter: Ecto.Adapters.Postgres, database: "elixir_china", username: "postgres", hostname: "localhost", extensions: [{Ecto.Adapters.Postgres.DateTime, []}, {Postgrex.Extensions.JSON, [library: Poison]}], port: 5432]
** (exit) exited in: :gen_server.call(#PID<0.192.0>, {:query, #Reference<0.0.2.1982>, :infinity}, 5000)
    ** (EXIT) %Postgrex.Error{message: "tcp connect: connection refused - :econnrefused", postgres: nil}
    (postgrex) lib/postgrex/connection.ex:97: Postgrex.Connection.query/4
    (ecto) lib/ecto/adapters/postgres/connection.ex:31: Ecto.Adapters.Postgres.Connection.query/4
    (ecto) lib/ecto/adapters/sql.ex:259: Ecto.Adapters.SQL.query/7
    (ecto) lib/ecto/pool.ex:159: Ecto.Pool.do_run/4
    (ecto) lib/ecto/adapters/sql.ex:247: Ecto.Adapters.SQL.query/6
    (ecto) lib/ecto/adapters/sql.ex:225: Ecto.Adapters.SQL.query/5
    (ecto) lib/ecto/adapters/sql.ex:183: Ecto.Adapters.SQL.query!/5
    (ecto) lib/ecto/adapters/postgres.ex:56: anonymous fn/4 in Ecto.Adapters.Postgres.execute_ddl/3
    (elixir) lib/enum.ex:1473: Enum."-reduce/3-lists^foldl/2-0-"/3
    (ecto) lib/ecto/adapters/postgres.ex:56: Ecto.Adapters.Postgres.execute_ddl/3
    (ecto) lib/ecto/migrator.ex:43: Ecto.Migrator.migrated_versions/2
    (ecto) lib/ecto/migrator.ex:142: Ecto.Migrator.run/4
    (ecto) lib/mix/tasks/ecto.migrate.ex:63: anonymous fn/4 in Mix.Tasks.Ecto.Migrate.run/2
    (elixir) lib/enum.ex:604: Enum."-each/2-lists^foreach/1-0-"/2
    (elixir) lib/enum.ex:604: Enum.each/2
    (mix) lib/mix/cli.ex:58: Mix.CLI.run_task/2
    (elixir) lib/code.ex:363: Code.require_file/2
```

**Comment by tony612** [comment]
I guess it's not the code's problem. You should ensure you have postgreSQL installed, it can be connected by the username and password and the user have the privilege to create db/db and so on

**Comment by mydearxym** [comment]
@tony612 thanks,  it is the postgreSQL issue, i think it should be documented in README.md.
